// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'contactContainer': string;
  'contactForm': string;
  'contactIcon': string;
  'contactLink': string;
  'contactLinkContainer': string;
  'contactLinkSubtitle': string;
  'contactLinkTitle': string;
}
export const cssExports: CssExports;
export default cssExports;
