// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'footer': string;
  'info': string;
  'navigator': string;
  'repo_link': string;
  'summary': string;
}
export const cssExports: CssExports;
export default cssExports;
