// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'detailedDescription': string;
  'dp': string;
  'dp_container': string;
  'dp_ring': string;
  'dp_ring_2': string;
  'expand_ring': string;
  'helloSection': string;
  'links': string;
  'oneLineDesc': string;
  'oneLiners': string;
  'subtext': string;
  'title': string;
  'titleIcons': string;
}
export const cssExports: CssExports;
export default cssExports;
