// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'detailedDescription': string;
  'helloSection': string;
  'oneLineDesc': string;
  'oneLiners': string;
  'subtext': string;
  'title': string;
  'titleIcons': string;
}
export const cssExports: CssExports;
export default cssExports;
