// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'skillTable': string;
  'skillTd': string;
  'skillTooltip': string;
  'skillsSection': string;
  'subsectionTitle': string;
  'subsectionTitleIcon': string;
  'techIcon': string;
  'titleIconTd': string;
}
export const cssExports: CssExports;
export default cssExports;
