// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'errorMsg': string;
  'honeypot': string;
  'inputs': string;
  'loader': string;
  'message': string;
  'messageError': string;
  'nameEmail': string;
  'nameEmailContainer': string;
  'submit': string;
}
export const cssExports: CssExports;
export default cssExports;
