// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'imgSelections': string;
  'imgSelectionsContainer': string;
  'imgSelectionsRow': string;
  'imgWithSelections': string;
  'mainImg': string;
}
export const cssExports: CssExports;
export default cssExports;
