// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'header': string;
  'logo': string;
  'navAndToggleContainer': string;
  'scrolled': string;
  'scrolledUp': string;
}
export const cssExports: CssExports;
export default cssExports;
