// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'closeIconContainer': string;
  'container': string;
  'drawerShadow': string;
  'navBg': string;
  'navDrawer': string;
  'slideIn': string;
  'slideOut': string;
}
export const cssExports: CssExports;
export default cssExports;
