// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'modal': string;
  'modalBg': string;
  'modalContent': string;
  'modalContentContainer': string;
  'modalHeader': string;
}
export const cssExports: CssExports;
export default cssExports;
