// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'contentContainer': string;
  'content_buttons_container': string;
  'description': string;
  'galleryWidthClasses': string;
  'liveLink': string;
  'liveLinkButton': string;
  'mainContainer': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
