// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'contentContainer': string;
  'description': string;
  'liveLink': string;
  'liveLinkButton': string;
  'mainContainer': string;
  'mainImg': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
