// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'tabHead': string;
  'tabHeadsContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
