// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bounce': string;
  'container': string;
  'scrollIcon': string;
}
export const cssExports: CssExports;
export default cssExports;
