// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'activeBar': string;
  'activeBarAnimated': string;
  'swipeLeft': string;
  'swipeRight': string;
  'swiperContainer': string;
  'swiperContent': string;
  'swiperStatusBars': string;
  'swiperStatusContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
