// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bulletsContainer': string;
  'calendar': string;
  'chevronDown': string;
  'container': string;
  'content': string;
  'contentAt': string;
  'contentTimeline': string;
  'contentTitle': string;
  'expanded': string;
  'leftContainer': string;
  'rightContainer': string;
  'rotated': string;
  'timeline': string;
  'titleAtContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
