// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actionsContainer': string;
  'card': string;
  'cardSubtitle': string;
  'cardText': string;
  'cardTextContainer': string;
  'cardTitle': string;
  'content': string;
  'descButtonsStackContainer': string;
  'galleryWidthClasses': string;
  'gitButton': string;
  'readMore': string;
  'subtitleSeparator': string;
  'techStackContainer': string;
  'techStackFacet': string;
  'techStackIcon': string;
  'textContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
